"""Generate a starter `ruststream` project tree."""

from pathlib import Path

_SERVICE_TEMPLATE = '''"""{name} -- starter RustStream service generated by `ruststream new`."""

import asyncio

from ruststream import MemoryBroker, Message, RustStream


broker = MemoryBroker(codec="json")


@broker.subscriber("orders")
async def handle(msg: Message) -> None:
    print(f"received: {{msg.value!r}}")


app = RustStream(broker, title="{name}")


async def _main() -> None:
    async with app:
        await broker.publish("orders", {{"id": 1, "name": "first"}})
        await asyncio.sleep(0.2)


if __name__ == "__main__":
    asyncio.run(_main())
'''


_PYPROJECT_TEMPLATE = """[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["ruststream"]
"""


_README_TEMPLATE = """# {name}

Generated by `ruststream new {name}`. Run with:

```
python -m {name}
```
"""


def scaffold(project: str, *, directory: Path) -> list[Path]:
    """Create `directory/<project>/` with a minimal service layout.

    Returns the list of files created.
    """
    root = directory / project
    if root.exists():
        raise FileExistsError(f"target directory {root} already exists")
    root.mkdir(parents=True)
    files: list[Path] = []

    service_path = root / "__init__.py"
    service_path.write_text(_SERVICE_TEMPLATE.format(name=project), encoding="utf-8")
    files.append(service_path)

    main_path = root / "__main__.py"
    main_path.write_text(f"from {project} import _main\n\nimport asyncio\n\nasyncio.run(_main())\n")
    files.append(main_path)

    pyproject_path = directory / f"{project}-pyproject.toml"
    pyproject_path.write_text(_PYPROJECT_TEMPLATE.format(name=project), encoding="utf-8")
    files.append(pyproject_path)

    readme_path = directory / f"{project}-README.md"
    readme_path.write_text(_README_TEMPLATE.format(name=project), encoding="utf-8")
    files.append(readme_path)

    return files


__all__: tuple[str, ...] = ("scaffold",)
